### ISSUE TITLE
Preparación de los tamaños

### ISSUE THREAD

**Issue by CristianGarzonBernal** [CristianGarzonBernal/Volando_mejor_planeacion#1]
Preparar las hojas para la elaboración de las naves

- [ ] 3 Hojas de una pulgada @CristianGarzonBernal 
- [ ] 3 hojas mas grandes que una pulgada @falacias
- [ ] 3 hojas mas grandes que las anteriores @falacias
